//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Менеждер_заказов.ModelDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MODBEntities : DbContext
    {
        public MODBEntities()
            : base("name=MODBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompletionStatu> CompletionStatus { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Performer> Performers { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskPerformer> TaskPerformers { get; set; }
        public virtual DbSet<TasksInTheProject> TasksInTheProjects { get; set; }
    }
}
