//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Менеждер_заказов.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.TasksInTheProjects = new HashSet<TasksInTheProject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> PlannedBudget { get; set; }
        public Nullable<int> ActualBudget { get; set; }
        public int idOrder { get; set; }
        public int idStatus { get; set; }
        public Nullable<int> idPerformer { get; set; }
    
        public virtual CompletionStatu CompletionStatu { get; set; }
        public virtual Order Order { get; set; }
        public virtual Performer Performer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasksInTheProject> TasksInTheProjects { get; set; }
    }
}
